Handle SIGINT signals
containers/netavark-dhcp-proxy pull request #18
Opened 2022-09-19 01:25 UTC by Jackbaude

Wait for a SIGINT signal from the process and clean up UDS socket before shutdown.

Signed-off-by: Jack <jackbaude@gmail.com>

2022-09-19 15:04 UTC, baude commented
you need to run the validator

2022-09-20 17:01 UTC, Jackbaude commented
@baude All checks passed. Please let me know thoughts on line 132 as mentioned above.

2022-09-21 13:54 UTC, baude commented on src/server.rs
>              log::error!("Could not find uds path");
error should have the fq path

2022-09-21 17:42 UTC, Luap99 reviewed
Is the problem here to we cannot bind the socket when it already exists?

In any case we have to remove the socket path before calling bind since we cannot guarantee that the path was removed, i.e. SIGKILL or just a crash.

2022-09-21 17:42 UTC, Luap99 commented on src/server.rs
> +        tokio::signal::ctrl_c()
you cannot handle sigkill, but we should handle sigterm as well

2022-09-21 18:32 UTC, flouthoc requested changes
You might wanna use https://docs.rs/tokio/latest/tokio/signal/unix/struct.SignalKind.html and directly process signal instead of top level implementation `ctrl_c` since there is no top level implementation for other signals.

Agree with @Luap99, this should handle `SIGTERM` as well

2022-09-21 18:38 UTC, flouthoc commented
Maybe something on the lines of ( you can remove unwrap in actual code)
```rs
tokio::signal::unix::signal(SignalKind::terminate()).unwrap().recv().await
```

2022-09-29 16:44 UTC, baude commented
please add a test

2022-10-02 21:34 UTC, Jackbaude commented
@baude ptal

2022-10-03 13:31 UTC, baude commented
/approve

2022-10-09 19:11 UTC, Jackbaude commented
@baude, @flouthoc, @Luap99. Is this PR ready to merge?

2022-10-10 13:44 UTC, baude commented
did you resolve all the comments from folks @Jackbaude ?

2022-10-10 14:25 UTC, flouthoc commented on src/server.rs
> +            _term = sigterm.recv() => {
```suggestion
            _ = sigterm.recv() => {
```

2022-10-10 14:26 UTC, flouthoc commented on src/server.rs
> +            _int = sigint.recv() => {
```suggestion
            _ = sigint.recv() => {
```

2022-10-10 14:29 UTC, flouthoc commented on src/server.rs
> +        std::process::exit(0x0100);
Is the reason for `0x0100`  to be `256` on windows or something else ?

2022-10-10 14:30 UTC, flouthoc commented
Some non-blocking nits but overall LGTM

2022-10-11 18:05 UTC, Jackbaude commented
> Some non-blocking nits but overall LGTM

@flouthoc Anything I can fix?

2022-10-11 18:10 UTC, flouthoc approved these changes
@Jackbaude thanks LGTM

2022-10-12 18:53 UTC, baude commented
/lgtm

2022-10-12 18:56 UTC, merged